---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp images $DEPLOYPATH
    - /bin/cp favicons $DEPLOYPATH
    - /bin/cp sanitize.css $DEPLOYPATH
    - /bin/cp animate.css $DEPLOYPATH
